### PR TITLE
update nodegroup name to sri

### PR DESCRIPTION
**Pull request by pabbathreddya2**

### CODE REVIEW

**Comment by gaurav** [comment]
I can confirm that the changes to helm/name-lookup, node-normalization-loader and node-normalization-web-server look fine, but I can't speak to the other changes.

**Review by maximusunc — APPROVED** [review]

**Comment by pabbathreddya2** [comment]
@EvanDietzMorris Can you pls approve this PR?

**Comment by maximusunc** [comment]
Hi @pabbathreddya2 I approved already. You should be good to go.

**Comment by pabbathreddya2** [comment]
@maximusunc Can you pls merge it. I don't see an option to merge.

**Comment by maximusunc** [comment]
Done!

**Pull request merged**
