### PR TITLE
Move api-watchdog to Sterling

### PR DESCRIPTION
**Pull request by maximusunc**

### CODE REVIEW

**Review by PhillipsOwen — CHANGES_REQUESTED** [review]
please adjust cronjob run time to be closer to midnight local time.

**Review by PhillipsOwen — CHANGES_REQUESTED** [review]
alter the time of the cron job to go off at midnight EST. 

the server time is UTC so /24 starts the run at ~7PM EST.

**Comment by maximusunc** [comment]
That's what I thought I did. I set the cronjob to run at `0 5 * * *`, so 5am UTC.

**Comment by maximusunc** [comment]
I only changed it in renci-prod values. Do you want it also changed in values.yaml?

**Comment by PhillipsOwen** [comment]
> I only changed it in renci-prod values. Do you want it also changed in values.yaml?

nope. prod is good. i see it in there now, thanks!

**Review by PhillipsOwen — APPROVED** [review]
looks good now...

**Review by YaphetKG — APPROVED** [review]

**Pull request merged**
