### PR TITLE
Added new changes for jenkins 

### PR DESCRIPTION
**Pull request by kannabhargav**

### CODE REVIEW

**Review by jdr0887 — CHANGES_REQUESTED** [review]
There will be other trapi-x.x releases in the future & we will likely need to support running multiple deployments.  Removing "-trapi-1.2" from the deployments file generalizes a parameter that needs to be version specific.

**Comment by kannabhargav** [comment]
We can fix those tags accordingly for the deployment if we have multiple images. I can specify those changes in values.yaml file which is on Jenkins.

**Comment by kannabhargav** [comment]
If it has multiple tags we can give them as per our requirement.

**Comment by jdr0887** [comment]
I am confused. 

I wrote these templates to work for me as I support this CAM-KP project.  You modified those templates to work with Jenkins.  Your modifications would break how I support this CAM-KP project going forward.  Code modifications that breaks how I deploy this software to our k8s instance, irregardless of the reason, renders this code useless to me.  I am going to argue that Jenkins is not the arbiter of modifications to the code.  Is there any way you could have Jenkins script around this obstacle?

**Comment by kannabhargav** [comment]
Okay, I understand now. let me try other way to fix this issue.

**Pull request closed without merging**
