### PR TITLE
ranker_to_prod

### PR DESCRIPTION
**Pull request by PhillipsOwen**
creating values file and ingress updates for ranker pod deploy

### CODE REVIEW

**Review by YaphetKG — COMMENTED** [review]
Does aragorn ranker need to be public ?

**Comment by PhillipsOwen** [comment]
> Does aragorn ranker need to be public ? If not this looks great

it always has been. sometimes its a good sanity check to go direct to that rather that via aragorn and friends

**Comment by YaphetKG** [comment]
> > Does aragorn ranker need to be public ? If not this looks great
> 
> it always has been. sometimes its a good sanity check to go direct to that rather that via aragorn and friends

Ah right, sorry, then this looks good, we can probably do that in a separate PR if there is the need.

**Review by YaphetKG — APPROVED** [review]
Does aragorn ranker need to be public ?

**Pull request merged**
