### PR TITLE
new cam-kp graph

### PR DESCRIPTION
**Pull request by EvanDietzMorris**

### CODE REVIEW

**Comment by gaurav** [comment]
Sorry for taking so long to get back to this! The tests from https://github.com/ExposuresProvider/cam-pipeline/pull/111 all pass (except for some CURIEs that we don't have information on), so I think Automat-CAM-KP looks good to me. I'll approve this PR now.

**Review by gaurav — APPROVED** [review]
Tested in https://github.com/ExposuresProvider/cam-pipeline/pull/111 and Automat-CAM-KP on RENCI-dev looks good to me!

**Comment by gaurav** [comment]
@YaphetKG Should I go ahead and merge this?

**Comment by YaphetKG** [comment]
fine by me, ill do that since am here ;)

**Pull request merged**
